spring:
  flyway:
    baseline-on-migrate: true
    enabled: false
    locations: classpath:db/migration

  application:
    name: zakat-management-system

  datasource:
    url: jdbc:mysql://localhost:3306/Zakat
    username: root
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 600       # 10 minutes
    refreshTokenExpiration: 604800   # 7 days

  mail:
    host: smtp.gmail.com
    port: 587
    username: ibrahim020105@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080